# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup and run Cordova
      uses: oxr463/setup-cordova@0.0.1
      with:
       exec: |
        cordova platform add android && \
        cordova build --no-telemetry && \
        cp "$(find . -name '*.apk')" .
        
    - name: Show the files
      shell: bash
      run: find . -print | grep -i \.apk
      
    - name: Publish GitHub Release 2
      uses: fnkr/github-action-ghr@v1
      env:
        GHR_PATH: platforms/android/app/build/outputs/apk/debug/app-debug.apk
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}